---
- name: AAS Host
  hosts: aas_host
  gather_facts: true
  pre_tasks:
    - name: Import playbook variables
      ansible.builtin.include_vars: "sapnwase-aas-vars.yml"
  roles:
    - sapnwaasreq
    - sapnwaasinst
...
